activemq:
    broker:
        url: tcp://biz-cn-activemq01.myfoscam.org:61616
auth:
    dubbo:
        version: 1.0.0-HW
cn:
    userzone:
        synurl: ''
com:
    userzone:
        synurl: ''
db:
    is:
        encrypt: 0
    login:
        password: IvyCamAccount#20190621%@lmtex
        username: account_user
    url: jdbc:mysql://biz-cn-mysql01.myfoscam.org:3306/db_account?autoReconnect=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
debug:
    model: false
dubbo:
    account:
        version: 1.0.0-HW
    cache:
        location: /home/admin/cache/dubbo/account-remoting.cache
    protocol:
        dubbo:
            port: 10000
    registry:
        url: biz-cn-zookeeper01.myfoscam.org:19555,biz-cn-zookeeper02.myfoscam.org:19555,biz-cn-zookeeper03.myfoscam.org:19555
livechat:
    email:
        address: 18487096609@163.com
log:
    app:
        level: INFO
    base:
        path: /home/ubuntu/logs/account
    common:
        level: INFO
    container:
        level: INFO
    dubbo:
        level: INFO
    foscam:
        level: INFO
    spring:
        level: INFO
    sql:
        level: INFO
mail:
    account:
        activate:
            url: https://test.myfoscam.com/user/active.html
    offical:
        account:
            activate:
                url: http://foscam.com:99/index/active
    sendflag: true
notification:
    dubbo:
        version: 1.0.0-HW
notify:
    email:
        address: 1350629834@qq.com
oem:
    web:
        user:
            data:
                request:
                    domain: https://notice.ivyiot.cn
outer:
    mail:
        sender: foscam@myfoscam.com
        sender.password: Fos554429
        smtp:
            host: smtp.myfoscam.com
            port: 25
platform:
    name: biz
portal:
    dubbo:
        version: 1.0.0-HW
push:
    url: https://push-access.myfoscam.cn:443
redis:
    master:
        password: FosCloud20170301@Fostar}%Random72894
    sentinel:
        master:
            name: cnbizmaster
        path1: biz-cn-redis-sentine01.myfoscam.org:26379
        path2: biz-cn-redis-sentine01.myfoscam.org:26379
        path3: biz-cn-redis-sentine01.myfoscam.org:26379
spring:
    datasource:
        config: classpath*:foscam_datasource_mysql_c3p0.xml
    orm:
        config: classpath*:foscam_mybatis_mysql_c3p0.xml
user:
    data:
        request:
            download: https://download.myfoscam.cn
web:
    portal:
        domain: https://www.myfoscam.cn
    project:
        name: account
    user:
        data:
            request:
                domain: https://extract.myfoscam.com
zone: cn
